baseURL = "https://cflien.me/"
theme = "LoveIt"
googleAnalytics = "G-75TS27309M"

defaultContentLanguage = "zh-tw"

[languages]
  [languages.zh-tw]
    title = "工程師的摳頂人生"
    languageName = ":taiwan:"
    weight = 1
    [[languages.zh-tw.menu.main]]
      name = "部落格"
      weight = 1
      url  = "posts/"
    [[languages.zh-tw.menu.main]]
      name = "關於我"
      weight = 2
      url = "about/"

[permalinks]
  posts = "/:year/:month/:title/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
